#!/usr/local/bin/node
const express = require("express");
const config = require("./src/utils/params");
const log = require("./src/utils/logger");
const StatRouter = require("./src/routers/static");
const ip = require("ip");
const HttpsHandler = require("./src/https/httpsHandler");

const app = express();
const staticRouter = new StatRouter(config);

app.use("/", staticRouter.getRrouter());

if (config.https) {
  try {
    let server = new HttpsHandler(config.https, app);
    server.loadCert();
    server.start();
    server.instance.listen(config.port, "0.0.0.0", () => {
      log.info(
        `Started Application, for preview Visit: https://${ip.address()}:${
          config.port
        }`
      );
    });
  } catch (e) {
    log.error(e.message);
  }
} else {
  app.listen(config.port, "0.0.0.0", () => {
    log.info(
      `Started Application, for preview Visit: http://${ip.address()}:${
        config.port
      }`
    );
  });
}
