#!/usr/bin/node
const express = require("express");
const config = require("./src/options/params");
const StatRouter = require("./src/routers/static");
const log = require("./src/utils/logger");

const app = express();
const staticRouter = new StatRouter(config);

app.use("/", staticRouter.getRrouter());

app.listen(config.port, () => {
  log.info("Started at port", config.port);
});
